### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by matheus3301** [matheus3301/TI0151-SistemasDistribuidos-UFC-2022.2#3]
# SMART HOME - TODO

Lista de coisas pra fazer

## Gateway
 - [x] Mensagem via multicast dizendo IP e PORTA do servidor central.

## Frontend
 - [x] Integrar com API utilizando protocol buffer
 - [x] Tela de dashboard
 - [x] Requisições para alterar estado de atuadores
 - [x] Requisitar periodicamente o estado de todos os sensores e atuadores
